# Generated by Django 5.0.6 on 2024-06-26 06:24

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('city', models.CharField(max_length=100)),
                ('city_ascii', models.CharField(blank=True, max_length=100)),
                ('city_alt', models.CharField(blank=True, max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('country', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('admin_name', models.CharField(blank=True, max_length=100)),
                ('admin_name_ascii', models.CharField(blank=True, max_length=100)),
                ('admin_code', models.CharField(blank=True, max_length=10)),
                ('admin_type', models.CharField(blank=True, max_length=50)),
                ('capital', models.CharField(blank=True, max_length=20)),
                ('density', models.IntegerField()),
                ('population', models.IntegerField()),
                ('population_proper', models.IntegerField()),
                ('timezone', models.CharField(max_length=50)),
                ('ranking', models.IntegerField()),
                ('same_name', models.BooleanField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('sector_code', models.CharField(max_length=100)),
                ('sector_label', models.CharField(max_length=255)),
                ('activity_code', models.CharField(max_length=100)),
                ('activity_label', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=100)),
                ('product_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('chef_lieu', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('population', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id_producer', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=100, null=True)),
                ('nrc', models.CharField(blank=True, max_length=100, null=True)),
                ('nat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sector_label', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='transactions.product')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.province')),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('enterprise', 'Enterprise'), ('individual', 'Individual')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=100, null=True)),
                ('nrc', models.CharField(blank=True, max_length=100, null=True)),
                ('nat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_label', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.country')),
                ('product', models.ManyToManyField(to='transactions.product')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.province')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('enterprise', 'Enterprise'), ('individual', 'Individual')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, max_length=100, null=True)),
                ('nrc', models.CharField(blank=True, max_length=100, null=True)),
                ('nat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sector_label', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.country')),
                ('product', models.ManyToManyField(to='transactions.product')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.province')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.client')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.supplier')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_purchase', models.IntegerField()),
                ('quantity_sale', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('net_stock_quantity', models.IntegerField()),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
