# Generated by Django 5.0.6 on 2024-07-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_with_tva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/transactions/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tva_rate',
            field=models.DecimalField(decimal_places=2, default=0.16, max_digits=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/clients/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.province'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/countries/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.ForeignKey(limit_choices_to={'country': 'Congo (Kinshasa)'}, on_delete=django.db.models.deletion.CASCADE, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/img/producers/'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.province'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/products/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/suppliers/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.province'),
        ),
        migrations.AlterField(
            model_name='uniquesector',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/uniquesectors/'),
        ),
    ]
