# Generated by Django 5.0.6 on 2024-06-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_province_chef_lieu_alter_province_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='admin_code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='admin_name_ascii',
        ),
        migrations.RemoveField(
            model_name='country',
            name='admin_type',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city_alt',
        ),
        migrations.RemoveField(
            model_name='country',
            name='density',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population_proper',
        ),
        migrations.RemoveField(
            model_name='country',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='country',
            name='same_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='timezone',
        ),
    ]
