# Generated by Django 5.0.6 on 2024-07-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_producer_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='img/transactions/'),
        ),
    ]
