# Generated by Django 5.0.6 on 2024-06-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_country_admin_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city',
        ),
        migrations.RemoveField(
            model_name='country',
            name='city_ascii',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
