# Generated by Django 5.0.6 on 2024-06-26 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_country_admin_name_remove_country_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UniqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(max_length=50)),
                ('sector_label', models.CharField(max_length=100)),
                ('activity_code', models.CharField(max_length=50)),
                ('activity_label', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('sector_code', 'sector_label', 'activity_code', 'activity_label')},
            },
        ),
        migrations.AlterField(
            model_name='producer',
            name='sector_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.uniqueproduct'),
        ),
    ]
