# Generated by Django 5.0.6 on 2024-07-24 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_client_name_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.province'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.province'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.province'),
        ),
    ]
