# Generated by Django 5.0.6 on 2024-06-26 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_producer_user_uniqueproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sector_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.uniqueproduct'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sector_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.uniqueproduct'),
        ),
    ]
