# Generated by Django 5.0.6 on 2024-07-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_client_country_alter_client_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('lb', 'Livre'), ('l', 'Litre'), ('ml', 'Millilitre'), ('m3', 'Mètre cube'), ('unit', 'Unité'), ('box', 'Boîte'), ('piece', 'Pièce'), ('m', 'Mètre'), ('cm', 'Centimètre'), ('mm', 'Millimètre'), ('inch', 'Pouce'), ('ft', 'Pied'), ('yd', 'Yard'), ('tonne', 'Tonne'), ('ton', 'Ton'), ('kWh', 'Kilowatt-heure'), ('Wh', 'Watt-heure'), ('other', 'Autre')], default='unit', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.producer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.product')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('producer', 'product', 'unit_of_measure')},
            },
        ),
    ]
