# Generated by Django 5.0.6 on 2024-06-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_client_sector_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='product',
            field=models.ManyToManyField(null=True, to='transactions.product'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='sector_label',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(null=True, to='transactions.product'),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='sector_label',
        ),
        migrations.AddField(
            model_name='client',
            name='sector_label',
            field=models.ManyToManyField(null=True, to='transactions.uniqueproduct'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sector_label',
            field=models.ManyToManyField(null=True, to='transactions.uniqueproduct'),
        ),
    ]
