# Generated by Django 5.0.6 on 2024-07-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit_of_measure',
            field=models.CharField(default='unit', max_length=10),
        ),
    ]
