# Generated by Django 5.0.6 on 2024-06-28 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_client_product_remove_client_sector_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='product',
            field=models.ManyToManyField(to='transactions.product'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sector_label',
            field=models.ManyToManyField(to='transactions.uniqueproduct'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(to='transactions.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sector_label',
            field=models.ManyToManyField(to='transactions.uniqueproduct'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='transactions.supplier'),
            preserve_default=False,
        ),
    ]
