# Generated by Django 5.0.6 on 2024-07-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_stock_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='unit_of_measure',
            field=models.CharField(choices=[('kg', 'Kilogramme'), ('g', 'Gramme'), ('lb', 'Livre'), ('l', 'Litre'), ('ml', 'Millilitre'), ('m3', 'Mètre cube'), ('unit', 'Unité'), ('box', 'Boîte'), ('piece', 'Pièce'), ('m', 'Mètre'), ('cm', 'Centimètre'), ('mm', 'Millimètre'), ('inch', 'Pouce'), ('ft', 'Pied'), ('yd', 'Yard'), ('tonne', 'Tonne'), ('ton', 'Ton'), ('kWh', 'Kilowatt-heure'), ('Wh', 'Watt-heure'), ('other', 'Autre')], default='unit', max_length=10),
        ),
    ]
