# Generated by Django 5.0.6 on 2024-06-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_country_options_transaction_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
