# Generated by Django 5.0.6 on 2024-06-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_delete_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniqueproduct',
            unique_together={('sector_code', 'sector_label')},
        ),
        migrations.RemoveField(
            model_name='uniqueproduct',
            name='activity_code',
        ),
        migrations.RemoveField(
            model_name='uniqueproduct',
            name='activity_label',
        ),
    ]
