# Generated by Django 5.0.6 on 2024-06-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_uniqueproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueProduct',
            new_name='UniqueSector',
        ),
        migrations.AlterModelOptions(
            name='uniquesector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
    ]
