# Generated by Django 5.0.6 on 2024-06-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_rename_uniqueproduct_uniquesector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_label'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='uniquesector',
            options={'ordering': ['sector_label'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
    ]
