# Generated by Django 5.0.6 on 2024-06-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_product_options_alter_uniquesector_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.producer'),
            preserve_default=False,
        ),
    ]
