# Generated by Django 5.0.6 on 2024-06-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_transaction_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='transactions.product'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sector_label',
            field=models.ManyToManyField(blank=True, null=True, to='transactions.uniquesector'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='transactions.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sector_label',
            field=models.ManyToManyField(blank=True, null=True, to='transactions.uniquesector'),
        ),
    ]
