# Generated by Django 5.0.6 on 2024-06-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_alter_client_product_alter_client_sector_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.province'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.ForeignKey(limit_choices_to={'country': 'Congo (Kinshasa)'}, on_delete=django.db.models.deletion.PROTECT, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.province'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.province'),
        ),
    ]
