# Generated by Django 5.0.6 on 2024-06-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_client_country_alter_client_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.supplier'),
        ),
    ]
