# Generated by Django 5.0.6 on 2024-06-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_transaction_currency_transaction_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='exchange_rate',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('CDF', 'Congolese Franc'), ('EUR', 'Euro')], default='CDF', max_length=3),
        ),
    ]
